// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Modelo;
//
//    var supermercado = Supermercado.FromJson(jsonString);

namespace MasterDetail
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Supermercado
    {
        [JsonProperty("ID")]
        public long Id { get; set; }

        [JsonProperty("SpmName")]
        public string SpmName { get; set; }

        [JsonProperty("LocalAddress")]
        public string LocalAddress { get; set; }

        [JsonProperty("Region")]
        public string Region { get; set; }

        [JsonProperty("City")]
        public string City { get; set; }
    }  
}
